export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';

export const FETCH_COMPLAINT_START = 'FETCH_COMPLAINT_START';
export const FETCH_COMPLAINT_SUCCESS = 'FETCH_COMPLAINT_SUCCESS';
export const FETCH_COMPLAINT_FAILURE = 'FETCH_COMPLAINT_FAILURE';

export const COMPLAINT_CREATE_START = 'COMPLAINT_CREATE_START';
export const COMPLAINT_CREATE_SUCCESS = 'COMPLAINT_CREATE_SUCCESS';
export const COMPLAINT_CREATE_FAILURE = 'COMPLAINT_CREATE_FAILURE';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILUER';

export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';