export const FETCH_SERVICES_GET_START = 'FETCH_SERVICES_GET_START';
export const FETCH_SERVICES_GET_SUCCESS = 'FETCH_SERVICES_GET_SUCCESS';
export const FETCH_SERVICES_GET_FAILURE = 'FETCH_SERVICES_GET_FAILURE';

export const FETCH_ORDER_GET_START = 'FETCH_ORDER_GET_START';
export const FETCH_ORDER_GET_SUCCESS = 'FETCH_ORDER_GET_SUCCESS';
export const FETCH_ORDER_GET_FAILURE = 'FETCH_ORDER_GET_FAILURE';

export const FETCH_ORDER_CREATE_START = 'FETCH_ORDER_CREATE_START';
export const FETCH_ORDER_CREATE_SUCCESS = 'FETCH_ORDER_CREATE_SUCCESS';
export const FETCH_ORDER_CREATE_FAILURE = 'FETCH_ORDER_CREATE_FAILURE';

export const FETCH_COMPLAINT_GET_START = 'FETCH_COMPLAINT_GET_START';
export const FETCH_COMPLAINT_GET_SUCCESS = 'FETCH_COMPLAINT_GET_SUCCESS';
export const FETCH_COMPLAINT_GET_FAILURE = 'FETCH_COMPLAINT_GET_FAILURE';

export const FETCH_COMPLAINT_CREATE_START = 'FETCH_COMPLAINT_CREATE_START';
export const FETCH_COMPLAINT_CREATE_SUCCESS = 'FETCH_COMPLAINT_CREATE_SUCCESS';
export const FETCH_COMPLAINT_CREATE_FAILURE = 'FETCH_COMPLAINT_CREATE_FAILURE';

export const FETCH_USER_GET_START = 'FETCH_USER_GET_START';
export const FETCH_USER_GET_SUCCESS = 'FETCH_USER_GET_SUCCESS';
export const FETCH_USER_GET_FAILURE = 'FETCH_USER_GET_FAILUSERS';

export const FETCH_USER_UPDATE_START = 'FETCH_USER_UPDATE_START';
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_UPDATE_SUCCESS';
export const FETCH_USER_UPDATE_FAILURE = 'FETCH_USER_UPDATE_FAILUSERS';