export const FETCH_CUSTOMER_SERVICE_START = "FETCH_CUSTOMER_SERVICE_START";
export const FETCH_CUSTOMER_SERVICE_SUCCESS = "FETCH_CUSTOMER_SERVICE_SUCCESS";
export const FETCH_CUSTOMER_SERVICE_FAILURE = "FETCH_CUSTOMER_SERVICE_FAILURE";

export const FETCH_CUSTOMER_SERVICES_START = "FETCH_CUSTOMER_SERVICES_START";
export const FETCH_CUSTOMER_SERVICES_SUCCESS = "FETCH_CUSTOMER_SERVICES_SUCCESS";
export const FETCH_CUSTOMER_SERVICES_FAILURE = "FETCH_CUSTOMER_SERVICES_FAILURE";

export const FETCH_CUSTOMER_SERVICES_NEW_START = "FETCH_CUSTOMER_SERVICES_NEW_START";
export const FETCH_CUSTOMER_SERVICES_NEW_SUCCESS = "FETCH_CUSTOMER_SERVICES_NEW_SUCCESS";
export const FETCH_CUSTOMER_SERVICES_NEW_FAILURE = "FETCH_CUSTOMER_SERVICES_NEW_FAILURE";

export const FETCH_CUSTOMER_SERVICES_ASSIGNED_START = "FETCH_CUSTOMER_SERVICES_ASSIGNED_START";
export const FETCH_CUSTOMER_SERVICES_ASSIGNED_SUCCESS = "FETCH_CUSTOMER_SERVICES_ASSIGNED_SUCCESS";
export const FETCH_CUSTOMER_SERVICES_ASSIGNED_FAILURE = "FETCH_CUSTOMER_SERVICES_ASSIGNED_FAILURE";

export const FETCH_CUSTOMER_SERVICES_TAKEN_START = "FETCH_CUSTOMER_SERVICES_TAKEN_START";
export const FETCH_CUSTOMER_SERVICES_TAKEN_SUCCESS = "FETCH_CUSTOMER_SERVICES_TAKEN_SUCCESS";
export const FETCH_CUSTOMER_SERVICES_TAKEN_FAILURE = "FETCH_CUSTOMER_SERVICES_TAKEN_FAILURE";

export const FETCH_CUSTOMER_SERVICES_DONE_START = "FETCH_CUSTOMER_SERVICES_DONE_START";
export const FETCH_CUSTOMER_SERVICES_DONE_SUCCESS = "FETCH_CUSTOMER_SERVICES_DONE_SUCCESS";
export const FETCH_CUSTOMER_SERVICES_DONE_FAILURE = "FETCH_CUSTOMER_SERVICES_DONE_FAILURE";