version: '3.5'
services:
  client:
    image: registry.chas.school/gold-client-staging:latest
    networks:
      - traefik
    deploy:
      labels:
        traefik.port: '80'
        traefik.backend: 'gold_client_staging'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:gold-staging.chas.school'
    env_file:
      - ../.env

networks:
  traefik:
    external: true