export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_SERVICES_NEW_START = 'FETCH_SERVICE_NEW_START';
export const FETCH_SERVICES_NEW_SUCCESS = 'FETCH_SERVICE_NEW_SUCCESS';
export const FETCH_SERVICES_NEW_FAILURE = 'FETCH_SERVICE_NEW_FAILURE';

export const FETCH_SERVICES_TAKEN_START = 'FETCH_SERVICE_TAKEN_START';
export const FETCH_SERVICES_TAKEN_SUCCESS = 'FETCH_SERVICE_TAKEN_SUCCESS';
export const FETCH_SERVICES_TAKEN_FAILURE = 'FETCH_SERVICE_TAKEN_FAILURE';

export const FETCH_SERVICES_DONE_START = 'FETCH_SERVICE_DONE_START';
export const FETCH_SERVICES_DONE_SUCCESS = 'FETCH_SERVICE_DONE_SUCCESS';
export const FETCH_SERVICES_DONE_FAILURE = 'FETCH_SERVICE_DONE_FAILURE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_INTERNAL_ORDER_START = 'FETCH_INTERNAL_ORDER_START';
export const FETCH_INTERNAL_ORDER_SUCCESS = 'FETCH_INTERNAL_ORDER_SUCCESS';
export const FETCH_INTERNAL_ORDER_FAILURE = 'FETCH_INTERNAL_ORDER_FAILURE';

export const FETCH_INTERNAL_ORDERS_START = 'FETCH_INTERNAL_ORDERS_START';
export const FETCH_INTERNAL_ORDERS_SUCCESS = 'FETCH_INTERNAL_ORDERS_SUCCESS';
export const FETCH_INTERNAL_ORDERS_FAILURE = 'FETCH_INTERNAL_ORDERS_FAILURE';

export const FETCH_COMPLAINT_START = 'FETCH_COMPLAINT_START';
export const FETCH_COMPLAINT_SUCCESS = 'FETCH_COMPLAINT_SUCCESS';
export const FETCH_COMPLAINT_FAILURE = 'FETCH_COMPLAINT_FAILURE';

export const FETCH_COMPLAINTS_START = 'FETCH_COMPLAINTS_START';
export const FETCH_COMPLAINTS_SUCCESS = 'FETCH_COMPLAINTS_SUCCESS';
export const FETCH_COMPLAINTS_FAILURE = 'FETCH_COMPLAINTS_FAILURE';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILUSERS';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILUSERS';

export const FETCH_CUSTOMERS_COMPANIES_START = 'FETCH_CUSTOMERS_COMPANIES_START';
export const FETCH_CUSTOMERS_COMPANIES_SUCCESS = 'FETCH_CUSTOMERS_COMPANIES_SUCCESS';
export const FETCH_CUSTOMERS_COMPANIES_FAILURE = 'FETCH_CUSTOMERS_COMPANIES_FAILURE';

export const FETCH_CUSTOMERS_PRIVATE_START = 'FETCH_CUSTOMERS_PRIVATE_START';
export const FETCH_CUSTOMERS_PRIVATE_SUCCESS = 'FETCH_CUSTOMERS_PRIVATE_SUCCESS';
export const FETCH_CUSTOMERS_PRIVATE_FAILURE = 'FETCH_CUSTOMERS_PRIVATE_FAILURE';

export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';