export const FETCH_SERVICE_START = "FETCH_SERVICE_START";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILURE = "FETCH_SERVICE_FAILURE";

// Incoming for employee
export const FETCH_EMP_INCOMING_REQUEST = "FETCH_EMP_INCOMING_REQUEST";
export const FETCH_EMP_INCOMING_SUCCESS = "FETCH_EMP_INCOMING_SUCCESS";
export const FETCH_EMP_INCOMING_FAILURE = "FETCH_EMP_INCOMING_FAILURE";

// Assigned for employee
export const FETCH_EMP_TAKEN_REQUEST = "FETCH_EMP_TAKEN_REQUEST";
export const FETCH_EMP_TAKEN_SUCCESS = "FETCH_EMP_TAKEN_SUCCESS";
export const FETCH_EMP_TAKEN_FAILURE = "FETCH_EMP_TAKEN_FAILURE";

// Done for employee
export const FETCH_EMP_DONE_REQUEST = "FETCH_EMP_DONE_REQUEST";
export const FETCH_EMP_DONE_SUCCESS = "FETCH_EMP_DONE_SUCCESS";
export const FETCH_EMP_DONE_FAILURE = "FETCH_EMP_DONE_FAILURE";
