export const FETCH_EMP_INCOMING_REQUEST = 'FETCH_EMP_INCOMING_REQUEST';
export const FETCH_EMP_INCOMING_SUCCESS = 'FETCH_EMP_INCOMING_SUCCESS';
export const FETCH_EMP_INCOMING_FAILURE = 'FETCH_EMP_INCOMING_FAILURE';