export const FETCH_EMP_INCOMING_REQUEST = 'FETCH_EMP_INCOMING_REQUEST';
export const FETCH_EMP_INCOMING_SUCCESS = 'FETCH_EMP_INCOMING_SUCCESS';
export const FETCH_EMP_INCOMING_FAILURE = 'FETCH_EMP_INCOMING_FAILURE';


export const FETCH_EMP_TAKEN_REQUEST = 'FETCH_EMP_TAKEN_REQUEST';
export const FETCH_EMP_TAKEN_SUCCESS = 'FETCH_EMP_TAKEN_SUCCESS';
export const FETCH_EMP_TAKEN_FAILURE = 'FETCH_EMP_TAKEN_FAILURE';



export const FETCH_EMP_DONE_REQUEST = 'FETCH_EMP_DONE_REQUEST';
export const FETCH_EMP_DONE_SUCCESS = 'FETCH_EMP_DONE_SUCCESS';
export const FETCH_EMP_DONE_FAILURE = 'FETCH_EMP_DONE_FAILURE';